/**
 * Örnek emlak ilanları - Backend (Spring Boot) bağlandığında API'den gelecek.
 */
export const featuredListings = [
  {
    id: "1",
    title: "Deniz Manzaralı Lüks Daire",
    location: "Kadıköy, İstanbul",
    price: "8.500.000 ₺",
    type: "Satılık",
    roomCount: "3+1",
    area: "145 m²",
    image: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&h=300&fit=crop",
  },
  {
    id: "2",
    title: "Bahçeli Müstakil Villa",
    location: "Çeşme, İzmir",
    price: "12.000.000 ₺",
    type: "Satılık",
    roomCount: "5+2",
    area: "320 m²",
    image: "https://images.unsplash.com/photo-1613490493576-7fde63acd811?w=400&h=300&fit=crop",
  },
  {
    id: "3",
    title: "Merkezi Konumda Ofis",
    location: "Levent, İstanbul",
    price: "45.000 ₺/ay",
    type: "Kiralık",
    roomCount: "Açık ofis",
    area: "180 m²",
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=400&h=300&fit=crop",
  },
  {
    id: "4",
    title: "Sahilde Yazlık Daire",
    location: "Bodrum, Muğla",
    price: "3.200.000 ₺",
    type: "Satılık",
    roomCount: "2+1",
    area: "95 m²",
    image: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&h=300&fit=crop",
  },
  {
    id: "5",
    title: "Yeni Proje 2+1 Daire",
    location: "Ataşehir, İstanbul",
    price: "5.750.000 ₺",
    type: "Satılık",
    roomCount: "2+1",
    area: "112 m²",
    image: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=400&h=300&fit=crop",
  },
  {
    id: "6",
    title: "Tarihi Yarımada Loft",
    location: "Sultanahmet, İstanbul",
    price: "28.000 ₺/ay",
    type: "Kiralık",
    roomCount: "1+1",
    area: "85 m²",
    image: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=400&h=300&fit=crop",
  },
  {
    id: "7",
    title: "Rezidans 4+1 Daire",
    location: "Beşiktaş, İstanbul",
    price: "15.200.000 ₺",
    type: "Satılık",
    roomCount: "4+1",
    area: "195 m²",
    image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=400&h=300&fit=crop",
  },
  {
    id: "8",
    title: "Şehir Merkezi 1+1",
    location: "Ankara, Çankaya",
    price: "18.500 ₺/ay",
    type: "Kiralık",
    roomCount: "1+1",
    area: "72 m²",
    image: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=400&h=300&fit=crop",
  },
  {
    id: "9",
    title: "Deniz Kenarı Penthouse",
    location: "Fethiye, Muğla",
    price: "22.000.000 ₺",
    type: "Satılık",
    roomCount: "5+2",
    area: "280 m²",
    image: "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=400&h=300&fit=crop",
  },
  {
    id: "10",
    title: "Sakin Semt 2+1 Daire",
    location: "Üsküdar, İstanbul",
    price: "22.000 ₺/ay",
    type: "Kiralık",
    roomCount: "2+1",
    area: "98 m²",
    image: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=400&h=300&fit=crop",
  },
  {
    id: "11",
    title: "Yeni Bina 3+1 Daire",
    location: "Nilüfer, Bursa",
    price: "4.100.000 ₺",
    type: "Satılık",
    roomCount: "3+1",
    area: "128 m²",
    image: "https://images.unsplash.com/photo-1600573472592-401b489a3cdc?w=400&h=300&fit=crop",
  },
  {
    id: "12",
    title: "Bahçeli Zemin Kat",
    location: "Bornova, İzmir",
    price: "35.000 ₺/ay",
    type: "Kiralık",
    roomCount: "3+1",
    area: "140 m²",
    image: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=400&h=300&fit=crop",
  },
];

/**
 * Detay sayfası için örnek ilan verisi.
 * Gerçek projede bu bilgiler backend'den /ilan/:id isteği ile gelecektir.
 */
export const adDetails = [
  {
    id: "1",
    fullTitle: "DOĞAN EMLAK GROUP'TAN İLKADIM KIŞLA'DA GENİŞ 2+1 2.KAT MASRAFSIZ",
    gallery: {
      totalImages: 4,
      images: [
        "https://images.unsplash.com/photo-1505691723518-36a5ac3be353?w=900&h=600&fit=crop",
        "https://images.unsplash.com/photo-1505691938895-1758d7feb511?w=900&h=600&fit=crop",
        "https://images.unsplash.com/photo-1484154218962-a197022b5858?w=900&h=600&fit=crop",
        "https://images.unsplash.com/photo-1505691723518-36a5ac3be353?w=900&h=600&fit=crop",
      ],
    },
    price: "3.100.000 TL",
    listingDate: "02.02.2026",
    listingNo: "1297921630",
    propertyType: "Satılık Daire",
    brutArea: "110",
    netArea: "100",
    roomCount: "2+1",
    buildingAge: "11-15 arası",
    floor: "2",
    totalFloors: "5",
    heating: "Kombi (Doğalgaz)",
    bathroomCount: "1",
    kitchenType: "Kapalı",
    personCapacity: "4",
    bedCount: "2",
    balcony: "Var",
    elevator: "Var",
    parking: "Açık Otopark",
    furnished: "Hayır",
    usageStatus: "Mülk Sahibi",
    inSite: "Hayır",
    creditAvailable: "Krediye Uygun",
    description:
      "SAMSUN İLKADIM KIŞLA MH GENİŞ 2+1 2.KAT ARAKAT AÇIK OTOPARKLI ASANSÖRLÜ KAMELYALI ÇİFT BALKONLU KATILIM VE FİNANS BANKALARINA UYGUN KREDİYE UYGUN MASRAFSIZ FIRSAT DAİRE",
    locationText: "Samsun, İlkadım, Kışla Mh.",
    features: [
      {
        title: "Cephe",
        columns: 4,
        items: [
          { label: "Batı", checked: true },
          { label: "Doğu", checked: true },
          { label: "Güney", checked: true },
          { label: "Kuzey", checked: true },
        ],
      },
      {
        title: "İç Özellikler",
        columns: 4,
        items: [
          { label: "ADSL" },
          { label: "Alarm (Yangın)" },
          { label: "Alaturka Tuvalet" },
          { label: "Akıllı Ev" },
          { label: "Alarm (Hırsız)" },
          { label: "Ankastre Fırın" },
          { label: "Barbekü", checked: true },
          { label: "Boyalı", checked: true },
          { label: "Bulaşık Makinesi" },
          { label: "Buzdolabı" },
          { label: "Çamaşır Kurutma Makinesi" },
          { label: "Çamaşır Makinesi" },
          { label: "Çamaşır Odası", checked: true },
          { label: "Çelik Kapı", checked: true },
          { label: "Duşakabin", checked: true },
          { label: "Fiber İnternet", checked: true },
          { label: "Ebeveyn Banyosu", checked: true },
          { label: "Giyinme Odası", checked: true },
          { label: "Gömme Dolap" },
          { label: "Görüntülü Diafon" },
          { label: "Hilton Banyo", checked: true },
          { label: "Isıcam", checked: true },
          { label: "Isı Yalıtımı", checked: true },
          { label: "Jakuzi" },
          { label: "Kartonpiyer", checked: true },
          { label: "Klima" },
          { label: "Laminant Zemin", checked: true },
          { label: "Mobilya" },
          { label: "Mutfak (Ankastre)", checked: true },
          { label: "Mutfak (Laminat)" },
          { label: "Parke Zemin", checked: true },
          { label: "Panjur/Jaluzi" },
          { label: "PVC Doğrama" },
          { label: "Seramik Zemin", checked: true },
          { label: "Set Üstü Ocak" },
          { label: "Spot Aydınlatma", checked: true },
          { label: "Şofben" },
          { label: "Teras" },
          { label: "Termosifon" },
          { label: "Wi-Fi" },
        ],
      },
      {
        title: "Dış Özellikler",
        columns: 4,
        items: [
          { label: "Araç Şarj İstasyonu" },
          { label: "24 Saat Güvenlik" },
          { label: "Apartman Görevlisi" },
          { label: "Buhar Odası" },
          { label: "Araç Şarj İstasyonu" },
          { label: "Hamam", checked: true },
          { label: "Kablo TV", checked: true },
          { label: "Müstakil Havuzlu", checked: true },
          { label: "Kamera Sistemi", checked: true },
          { label: "Isı Yalıtımı", checked: true },
          { label: "Ses Yalıtımı", checked: true },
          { label: "Spor Alanı" },
          { label: "Su Deposu" },
          { label: "Tenis Kortu" },
          { label: "Uydu", checked: true },
          { label: "Yüzme Havuzu (Açık)", checked: true },
        ],
      },
      {
        title: "Muhit",
        columns: 4,
        items: [
          { label: "Alışveriş Merkezi" },
          { label: "Belediye" },
          { label: "Cami", checked: true },
          { label: "Cemevi" },
          { label: "Denize Sıfır" },
          { label: "Eczane", checked: true },
          { label: "Eğlence Merkezi" },
          { label: "Fuar" },
          { label: "Göle Sıfır" },
          { label: "Hastane" },
          { label: "Market", checked: true },
          { label: "Sağlık Ocağı", checked: true },
          { label: "Park" },
          { label: "Polis Merkezi" },
          { label: "Semt Pazarı" },
          { label: "Spor Salonu" },
        ],
      },
      {
        title: "Ulaşım",
        columns: 4,
        items: [
          { label: "Anayol", checked: true },
          { label: "Avrasya Tüneli" },
          { label: "Boğaz Köprüleri" },
          { label: "Cadde", checked: true },
          { label: "Dolmuş", checked: true },
          { label: "Otobüs Durağı", checked: true },
          { label: "Metro" },
          { label: "Metrobüs" },
          { label: "Marmaray" },
          { label: "Tramvay" },
        ],
      },
      {
        title: "Manzara",
        columns: 4,
        items: [
          { label: "Boğaz" },
          { label: "Deniz" },
          { label: "Doğa", checked: true },
          { label: "Göl" },
          { label: "Havuz", checked: true },
          { label: "Nehir" },
          { label: "Park & Yeşil Alan" },
          { label: "Şehir" },
        ],
      },
      {
        title: "Konut Tipi",
        columns: 4,
        items: [
          { label: "Dubleks" },
          { label: "En Üst Kat" },
          { label: "Ara Kat" },
          { label: "Ara Kat Dubleks" },
          { label: "Bahçe Dubleksi" },
          { label: "Çatı Dubleksi" },
          { label: "Forleks" },
          { label: "Ters Dubleks" },
          { label: "Tripleks" },
        ],
      },
      {
        title: "Engelliye ve Yaşlıya Uygun",
        columns: 4,
        items: [
          { label: "Araç Park Yeri" },
          { label: "Engelliye Uygun Asansör" },
          { label: "Engelliye Uygun Banyo" },
          { label: "Engelliye Uygun Mutfak" },
          { label: "Engelliye Uygun Park" },
          { label: "Geniş Koridor" },
          { label: "Giriş / Rampa" },
          { label: "Merdiven" },
          { label: "Tutamak / Korkuluk" },
          { label: "Yüzme Havuzu" },
        ],
      },
    ],
  },
];
